### ISSUE TITLE
Octomation服务异常，报No route to host

### ISSUE THREAD

**Issue by wuzhi-dev** [flagify-com/OctoMation#125]
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 61 common frames omitted

**Comment by wuzhi-dev** [comment]
初步排查是docker的网络出了问题，sudo systemctl restart docker重启docker，然后重启服务

**Comment by wuzhi-dev** [comment]
重启docker和Octomation后服务正常
