### ISSUE TITLE
zookeeper服务未知异常退出

### ISSUE THREAD

**Issue by wuzhi-dev** [flagify-com/OctoMation#131]
2024-08-19 10:25:21,244 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@373] - Close of session 0x0
java.io.IOException: ZooKeeperServer not running
 at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:544)
 at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:332)
 at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
 at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)
2024-08-19 10:25:21,350 [myid:1] - INFO  [main:DataTree@1730] - The digest in the snapshot has digest version of 2, , with zxid as 0xf181d, and digest value as 2402914254563
2024-08-19 10:25:22,050 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2024-08-19 10:25:22,053 [myid:1] - ERROR [main:ZooKeeperServerMain@90] - Unexpected exception, exiting abnormally
java.io.EOFException
 at java.base/java.io.DataInputStream.readInt(Unknown Source)
 at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
 at org.apache.zookeeper.server.persistence.FileHeader.deserialize(FileHeader.java:67)
 at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.inStreamCreated(FileTxnLog.java:725)
 at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.createInputArchive(FileTxnLog.java:743)
 at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.goToNextLog(FileTxnLog.java:711)
 at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.next(FileTxnLog.java:792)
 at org.apache.zookeeper.server.persistence.FileTxnSnapLog.fastForwardFromEdits(FileTxnSnapLog.java:352)
 at org.apache.zookeeper.server.persistence.FileTxnSnapLog.lambda$restore$0(FileTxnSnapLog.java:258)
 at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:303)
 at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:285)
 at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:494)
 at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:665)
 at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:758)
 at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:130)
 at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:159)
 at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:112)
 at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:67)
 at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:140)
 at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2024-08-19 10:25:22,056 [myid:1] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1

**Comment by wuzhi-dev** [comment]
处理：
1.删除zk的数据文件 version2
2.删除kafka的meta.peroperties文件
3.重启
4.进入shakespeare-mgmt执行shakespeare-mgmt init

**Comment by Iceqaq** [comment]
你好  能否更详细，这个shakespeare-mgmt 我没大理解

**Comment by wuzhi-dev** [comment]
> 你好 能否更详细，这个shakespeare-mgmt 我没大理解

通过docker ps查看有个shakespeare-mgmt的容器，进入到容器的命令行里执行命令
