### ISSUE TITLE
PYSERVER状态丢失
health check py server error, no py server

Caused by:java.net.UnknownHostException: py

### ISSUE THREAD

**Issue by wuzhi-dev** [flagify-com/OctoMation#62]
PYSERVER状态丢失
health check py server error, no py server

Caused by:java.net.UnknownHostException: py.sp.com: Name or service not known

**Comment by wzfukui** [comment]
用户运行截图
![image](https://github.com/flagify-com/OctoMation/assets/146505187/e758c5b1-1b9a-4759-83f5-3014158e2e3a)

```
health check py server error,no py server
health check py server error, no py server
health check py server error,no py server
```
![image](https://github.com/flagify-com/OctoMation/assets/146505187/b0b53183-7f14-4d59-b973-8d5c7836df59)

```
at org.apache.tomcat.util.threads,TaskThreadsWrappingRunnable. run
at java. Lang .Thread . run(Thread . java : 748)Caused by:java.net.UnknownHostException: py.sp.com: Name or service not knownat java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.iava:929)at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)at java.net.InetAddress.getAllByName0(InetAddress.java:1277)at java.net.InetAddress.getAllByName(InetAddress.java:1193at java.net.InetAddress.getAllByName(InetAddress.java:1127)
```
![image](https://github.com/flagify-com/OctoMation/assets/146505187/f90b03d8-9b9f-4d6f-a8d4-9635407330e6)

**Comment by wzfukui** [comment]
<img width="1119" alt="image" src="https://github.com/flagify-com/OctoMation/assets/146505187/2f8c66b8-8f7c-4357-a8cd-dad4e2427ba6">

PYSERVER挂在ACTION引擎上，可以尝试重启ACTION容器
```bash
docker-compose -f /opt/shakespeare/docker-compose.yml  stop shakespeare-action
docker-compose -f /opt/shakespeare/docker-compose.yml  start shakespeare-action
```
建议同步看下其他docker运行状态：`docker ps`

最好能提供详细的日志上下文，便于开发人员分析，定位根因。
